/* constants - list of things */
const arrayOfArtists = [
  "Pablo Picasso",
  "Paul Cezanne",
  "Gustav Klimt",
  "Claude Monet",
  "Marcel Duchamp",
  "Henri Matisse",
  "Jackson Pollock",
  "Andy Warhol",
  "Willem De Kooning",
  "Piet Mondrian",
  "Paul Gauguin",
  "Francis Bacon",
  "Robert Rauschenberg",
  "Georges Braque",
  "Wassily Kandinsky",
  "Constantin Brancusi",
  "Kasimir Malevich",
  "Jasper Johns",
  "Frida Kahlo",
  "Martin Kippenberger",
  "Paul Klee",
  "Egon Schiele",
  "Donald Judd",
  "Bruce Nauman",
  "Alberto Giacometti",
  "Salvador Dalí",
  "Auguste Rodin",
  "Mark Rothko",
  "Edward Hopper",
  "Lucian Freud",
  "Richard Serra",
  "Rene Magritte",
  "David Hockney",
  "Philip Guston",
  "Henri Cartier-Bresson",
  "Pierre Bonnard",
  "Jean-Michel Basquiat",
  "Max Ernst",
  "Diane Arbus",
  "Georgia O'Keeffe",
  "Cy Twombly",
  "Max Beckmann",
  "Barnett Newman",
  "Giorgio De Chirico",
  "Roy Lichtenstein",
  "Edvard Munch",
  "Pierre Auguste Renoir",
  "Man Ray",
  "Henry Moore",
  "Cindy Sherman",
  "Jeff Koons",
  "Tracey Emin",
  "Damien Hirst",
  "Yves Klein",
  "Henri Rousseau",
  "Chaim Soutine",
  "Arshile Gorky",
  "Amedeo Modigliani",
  "Umberto Boccioni",
  "Jean Dubuffet",
  "Eva Hesse",
  "Edouard Vuillard",
  "Carl Andre",
  "Juan Gris",
  "Lucio Fontana",
  "Franz Kline",
  "David Smith",
  "Joseph Beuys",
  "Alexander Calder",
  "Louise Bourgeois",
  "Marc Chagall",
  "Gerhard Richter",
  "Balthus",
  "Joan Miro",
  "Ernst Ludwig Kirchner",
  "Frank Stella",
  "Georg Baselitz",
  "Francis Picabia",
  "Jenny Saville",
  "Dan Flavin",
  "Alfred Stieglitz",
  "Anselm Kiefer",
  "Matthew Barney",
  "George Grosz",
  "Bernd And Hilla Becher",
  "Sigmar Polke",
  "Brice Marden",
  "Maurizio Cattelan",
  "Sol LeWitt",
  "Chuck Close",
  "Edward Weston",
  "Joseph Cornell",
  "Karel Appel",
  "Bridget Riley",
  "Alexander Archipenko",
  "Anthony Caro",
  "Richard Hamilton",
  "Clyfford Still",
  "Luc Tuymans",
  "Claes Oldenburg",
  "Eduardo Paolozzi",
  "Frank Auerbach",
  "Dinos and Jake Chapman",
  "Marlene Dumas",
  "Antoni Tapies",
  "Giorgio Morandi",
  "Walker Evans",
  "Nan Goldin",
  "Robert Frank",
  "Georges Rouault",
  "Jean Arp",
  "August Sander",
  "James Rosenquist",
  "Andreas Gursky",
  "Eugene Atget",
  "Jeff Wall",
  "Ellsworth Kelly",
  "Bill Brandt",
  "Christo And Jeanne Claude",
  "Howard Hodgkin",
  "Josef Albers",
  "Piero Manzoni",
  "Agnes Martin",
  "Anish Kapoor",
  "L.S. Lowry",
  "Robert Motherwell",
  "Robert Delaunay",
  "Stuart Davis",
  "Ed Ruscha",
  "Gilbert & George",
  "Stanley Spencer",
  "James Ensor",
  "Fernand Leger",
  "Brassai (Gyula Halasz)",
  "Alexander Rodchenko",
  "Robert Ryman",
  "Ad Reinhardt",
  "Hans Bellmer",
  "Isa Genzken",
  "Kees Van Dongen",
  "Weegee",
  "Paula Rego",
  "Thomas Hart Benton",
  "Hans Hofmann",
  "Vladimir Tatlin",
  "Odilon Redon",
  "George Segal",
  "Jorg Immendorff",
  "Robert Smithson",
  "Peter Doig",
  "Ed and Nancy Kienholz",
  "Richard Prince",
  "Ansel Adams",
  "Naum Gabo",
  "Diego Rivera",
  "Barbara Hepworth",
  "Nicolas De Stael",
  "Walter De Maria",
  "Felix Gonzalez-Torres",
  "Giacomo Balla",
  "Ben Nicholson",
  "Anthony Gormley",
  "Lyonel Feininger",
  "Emil Nolde",
  "Mark Wallinger",
  "Hermann Nitsch",
  "Paul Signac",
  "Jean Tinguely",
  "Kurt Schwitters",
  "Grayson Perry",
  "Julian Schnabel",
  "Raymond Duchamp-Villon",
  "Robert Gober",
  "Duane Hanson",
  "Richard Diebenkorn",
  "Alex Katz",
  "Alighiero E Boetti",
  "Henri Gaudier-Brzeska",
  "Laszlo Moholy-Nagy",
  "Jacques-Henri Lartigue",
  "Robert Morris",
  "Sarah Lucas",
  "Jannis Kounellis",
  "Chris Burden",
  "Otto Dix",
  "David Bomberg",
  "Fischli & Weiss",
  "Augustus John",
  "Marsden Hartley",
  "Takashi Murakami",
  "James Turrell",
  "Isamu Noguchi",
  "Robert Mangold",
  "John Chamberlain",
  "Charles Demuth",
  "John Currin",
  "Alberto Burri",
  "Arnulf Rainer",
  "David Salle",
  "Hiroshi Sugimoto",
];

const arrayOfObjects = [
  "A bicycle",
  "A book",
  "A camera",
  "A car",
  "A chair",
  "A clock",
  "A computer",
  "A cup",
  "A desk",
  "A dog",
  "A door",
  "A drum",
  "A duck",
  "A elephant",
  "A fan",
  "A flower",
  "A guitar",
  "A hat",
  "A helicopter",
  "A horse",
  "A house",
  "A key",
  "A knife",
  "A lamp",
  "A laptop",
  "A leaf",
  "A microphone",
  "A mirror",
  "A mouse",
  "A pen",
  "A pencil",
  "A phone",
  "A piano",
  "A pillow",
  "A plane",
  "A plant",
  "A radio",
  "A remote",
  "A ring",
  "A robot",
  "A rock",
  "A rope",
  "A rug",
  "A ruler",
  "A sandwich",
  "A scissors",
  "A screwdriver",
  "A shoe",
  "A sofa",
  "A spoon",
  "A stapler",
  "A statue",
  "A table",
  "A telephone",
  "A telescope",
  "A tent",
  "A toaster",
  "A toothbrush",
  "A tree",
  "A trumpet",
  "A TV",
  "A typewriter",
  "A umbrella",
  "A vase",
  "A violin",
  "A watch",
  "A wheel",
  "A whistle",
  "A window",
  "A wrench",
  "A yacht",
  "A yo-yo",
  "A zipper",
  "A bag",
  "A ball",
  "A balloon",
  "A banana",
  "A bat",
  "A bed",
  "A bee",
  "A bird",
  "A boat",
  "A bone",
  "A bookcase",
  "A boot",
  "A bottle",
  "A box",
  "A bread",
  "A brick",
  "A bridge",
  "A broom",
  "A brush",
  "A bucket",
  "A butterfly",
  "A cake",
  "A calculator",
  "A calendar",
  "A camera",
  "A candle",
  "A candy",
  "A canvas",
  "A car",
  "A card",
  "A carrot",
  "A castle",
  "A cat",
  "A CD",
  "A cell phone",
  "A chalk",
  "A cheese",
  "A chess",
  "A chicken",
  "A chocolate",
  "A church",
  "A cigarette",
  "A circus",
  "A clock",
  "A cloud",
  "A coffee",
  "A coin",
  "A computer",
  "A cookie",
  "A corn",
  "A cow",
  "A crab",
  "A crayon",
  "A cream",
  "A crocodile",
  "A crow",
  "A cup",
  "A curtain",
  "A cushion",
  "A diamond",
  "A dinosaur",
  "A disc",
  "A dish",
  "A dog",
  "A dolphin",
  "A donkey",
  "A door",
  "A dragon",
  "A dress",
  "A drink",
  "A drum",
  "A duck",
  "A DVD",
  "A ear"];

let buttonTarget = document.getElementById("print-message");

const randomWordGenerator = () => {
  let object1Number = Math.floor(Math.random() * arrayOfObjects.length);
  let artist1Number = Math.floor(Math.random() * arrayOfArtists.length);

  buttonTarget.innerHTML = `${
    arrayOfObjects[object1Number]
  } in the style of ${
    arrayOfArtists[artist1Number]
  }`;
};
