/* constants - list of things */
const arrayOfArtists = [  "Pablo Picasso",  "Leonardo da Vinci",  "Vincent van Gogh",  "Michelangelo",  "Claude Monet",  "Salvador Dali",  "Rembrandt",  "Johannes Vermeer",  "Henri Matisse",  "Edvard Munch",  "Gustav Klimt",  "Frida Kahlo",  "Georgia O'Keeffe",  "Diego Rivera",  "Yayoi Kusama",  "David Hockney",  "Banksy",  "Shepard Fairey",  "JR",  "Olafur Eliasson",  "Edward Hopper",  "Norman Rockwell",  "Andy Warhol",  "Roy Lichtenstein",  "Keith Haring",  "Jean-Michel Basquiat",  "Damien Hirst",  "Jeff Koons",  "Jackson Pollock",  "Willem de Kooning",  "Mark Rothko",  "Ellsworth Kelly",  "Richard Serra",  "Anish Kapoor",  "Hans Holbein the Younger",  "Peter Paul Rubens",  "Jan van Eyck",  "Hieronymus Bosch",  "Pieter Bruegel the Elder",  "Titian",  "Caravaggio",  "Raphael",  "Sandro Botticelli",  "Jan Vermeer",  "Frans Hals",  "Johannes Vermeer",  "Anthony van Dyck",  "Jan Steen",  "Pieter Claesz",  "Adriaen Brouwer",  "Rembrandt van Rijn",  "Johannes Vermeer",  "Jan van Goyen",  "Johannes Vermeer",  "Jan Brueghel the Elder",  "Rubens",  "Johannes Vermeer",  "Gerard ter Borch",  "Aelbert Cuyp",  "Jan Davidsz de Heem",  "Jacob van Ruisdael",  "Jan Weenix",  "Paul Cézanne",  "Georges Seurat",  "Henri Rousseau",  "Piet Mondrian",  "Marcel Duchamp",  "Max Ernst",  "Joan Miró",  "Salvador Dalí",  "Francis Bacon",  "Lucian Freud",  "David Hockney",  "Bridget Riley",  "Anselm Kiefer",  "Gerhard Richter",  "Sigmar Polke",  "Cindy Sherman",  "Barbara Kruger",  "Kara Walker",  "Yoko Ono",  "David Wojnarowicz",  "Chris Ofili",  "Takashi Murakami",  "Yoshitomo Nara",  "Kaws",  "Ai Weiwei",  "Damien Hirst",  "Grayson Perry",  "Tracey Emin",  "Shirin Neshat",  "Zhang Xiaogang",  "Wang Guangyi",  "Liu Xiaodong",  "Xu Bing",  "Zeng Fanzhi"];

const arrayOfObjects = [
  "A bicycle",
  "A book",
  "A camera",
  "A car",
  "A chair",
  "A clock",
  "A computer",
  "A cup",
  "A desk",
  "A dog",
  "A door",
  "A drum",
  "A duck",
  "A elephant",
  "A fan",
  "A flower",
  "A guitar",
  "A hat",
  "A helicopter",
  "A horse",
  "A house",
  "A key",
  "A knife",
  "A lamp",
  "A laptop",
  "A leaf",
  "A microphone",
  "A mirror",
  "A mouse",
  "A pen",
  "A pencil",
  "A phone",
  "A piano",
  "A pillow",
  "A plane",
  "A plant",
  "A radio",
  "A remote",
  "A ring",
  "A robot",
  "A rock",
  "A rope",
  "A rug",
  "A ruler",
  "A sandwich",
  "A scissors",
  "A screwdriver",
  "A shoe",
  "A sofa",
  "A spoon",
  "A stapler",
  "A statue",
  "A table",
  "A telephone",
  "A telescope",
  "A tent",
  "A toaster",
  "A toothbrush",
  "A tree",
  "A trumpet",
  "A TV",
  "A typewriter",
  "A umbrella",
  "A vase",
  "A violin",
  "A watch",
  "A wheel",
  "A whistle",
  "A window",
  "A wrench",
  "A yacht",
  "A yo-yo",
  "A zipper",
  "A bag",
  "A ball",
  "A balloon",
  "A banana",
  "A bat",
  "A bed",
  "A bee",
  "A bird",
  "A boat",
  "A bone",
  "A bookcase",
  "A boot",
  "A bottle",
  "A box",
  "A bread",
  "A brick",
  "A bridge",
  "A broom",
  "A brush",
  "A bucket",
  "A butterfly",
  "A cake",
  "A calculator",
  "A calendar",
  "A camera",
  "A candle",
  "A candy",
  "A canvas",
  "A car",
  "A card",
  "A carrot",
  "A castle",
  "A cat",
  "A CD",
  "A cell phone",
  "A chalk",
  "A cheese",
  "A chess",
  "A chicken",
  "A chocolate",
  "A church",
  "A cigarette",
  "A circus",
  "A clock",
  "A cloud",
  "A coffee",
  "A coin",
  "A computer",
  "A cookie",
  "A corn",
  "A cow",
  "A crab",
  "A crayon",
  "A cream",
  "A crocodile",
  "A crow",
  "A cup",
  "A curtain",
  "A cushion",
  "A diamond",
  "A dinosaur",
  "A disc",
  "A dish",
  "A dog",
  "A dolphin",
  "A donkey",
  "A door",
  "A dragon",
  "A dress",
  "A drink",
  "A drum",
  "A duck",
  "A DVD",
  "A ear"];

let buttonTarget = document.getElementById("print-message");

const randomWordGenerator = () => {
  let object1Number = Math.floor(Math.random() * arrayOfObjects.length);
  let artist1Number = Math.floor(Math.random() * arrayOfArtists.length);

  buttonTarget.innerHTML = `${
    arrayOfObjects[object1Number]
  } in the style of ${
    arrayOfArtists[artist1Number]
  }`;
};
